steps:
    ###########################################################################
    # Build the image using Kaniko and push to Artifact Registry
    -   id: build
        name: "gcr.io/kaniko-project/executor:latest"
        args:
        - --dockerfile=advent-of-code/Dockerfile,
        - --context=dir://advent-of-code,
        - --cache=true,
        - --cache-ttl=24h,
        - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/containers/advent-of-code:$SHORT_SHA

    # Deploy image to Cloud Run
    -   id: deploy
        name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
        entrypoint: gcloud
        args:
            - "run"
            - "deploy"
            - "advent-of-code"
            - "--image"
            - "us-central1-docker.pkg.dev/$PROJECT_ID/containers/advent-of-code:$SHORT_SHA"
            - "--region"
            - "us-central1"
            - "--platform"
            - "managed"
        waitFor:
            - build

# 10 minutes
timeout: 600s

images:
    - "us-central1-docker.pkg.dev/$PROJECT_ID/containers/advent-of-code:$SHORT_SHA"
    - "us-central1-docker.pkg.dev/$PROJECT_ID/containers/advent-of-code:latest"
