# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Fletcher Easton

watch:
    - .

theme:
    name: material
    logo: images/logo.png
    favicon: images/favicon.ico

    palette:
        # Palette toggle for light mode
        -   scheme: default
            primary: deep-purple
            accent: pink
            toggle:
                icon: material/brightness-7
                name: Switch to dark mode

        # Palette toggle for dark mode
        -   scheme: slate
            primary: deep-purple
            accent: pink
            toggle:
                icon: material/brightness-4
                name: Switch to light mode

    icon:
        admonition:
            info: material/alert-box-outline

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.indexes
        - navigation.footer
        - navigation.top
        - toc.integrate
        - toc.follow
        - content.tabs.link
        - content.code.copy

plugins:
    - search

markdown_extensions:
    # Callouts
    - admonition
    - pymdownx.details
    - pymdownx.superfences

    # Tabs
    - pymdownx.superfences
    -   pymdownx.tabbed:
            alternate_style: true

    # MathJax
    -   pymdownx.arithmatex:
            generic: true

    # Table of contents
    - toc:
        permalink: true

    # Tasklists
    - pymdownx.tasklist

    # HTML
    - md_in_html
    - attr_list

extra_css:
    - css/images.css

extra_javascript:
    - javascript/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fletcheaston

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fletcheaston/

nav:
    - Resume: index.md
    - MyFreightCube: projects/my-freight-cube.md
    - Advent of Code - 2023:
        - projects/advent-of-code/2023/index.md
        - "Day 1: Trebuchet?!": projects/advent-of-code/2023/day-1.md
        - "Day 2: Code Conundrum": projects/advent-of-code/2023/day-2.md
        - "Day 3: Gear Ratios": projects/advent-of-code/2023/day-3.md
        - "Day 4: Scratchcards": projects/advent-of-code/2023/day-4.md
        - "Day 5: If You Give A Seed A Fertilizer": projects/advent-of-code/2023/day-5.md
        - "Day 6: Wait For It": projects/advent-of-code/2023/day-6.md
    - Advent of TypeScript - 2023:
        - projects/advent-of-typescript/index.md
        - "Day 1: Christmas Cookies": projects/advent-of-typescript/2023/day-1.md
        - "Day 2: Christmas Cookie Inventory": projects/advent-of-typescript/2023/day-2.md
        - "Day 3: The Gift Wrapper": projects/advent-of-typescript/2023/day-3.md
        - "Day 4: Christmas Present Delivery Addresses": projects/advent-of-typescript/2023/day-4.md
        - "Day 5: Organize Santa's List": projects/advent-of-typescript/2023/day-5.md
        - "Day 6: Filtering The Children (part 1)": projects/advent-of-typescript/2023/day-6.md
        - "Day 7: Filtering The Children (part 2)": projects/advent-of-typescript/2023/day-7.md
    - Advent of Code - 2022:
        - projects/advent-of-code/2022/index.md
        - "Day 1: Calorie Counting": projects/advent-of-code/2022/day-1.md
        - "Day 2: Rock Paper Scissors": projects/advent-of-code/2022/day-2.md
        - "Day 3: Rucksack Reorganization": projects/advent-of-code/2022/day-3.md
        - "Day 4: Camp Cleanup": projects/advent-of-code/2022/day-4.md
        - "Day 5: Supply Stacks": projects/advent-of-code/2022/day-5.md
        - "Day 6: Tuning Trouble": projects/advent-of-code/2022/day-6.md
        - "Day 7: No Space Left On Device": projects/advent-of-code/2022/day-7.md
