# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Fletcher Easton

watch:
    - .

theme:
    name: material
    logo: images/logo.png
    favicon: images/favicon.ico

    palette:
        # Palette toggle for light mode
        -   scheme: default
            primary: deep-purple
            accent: pink
            toggle:
                icon: material/brightness-7
                name: Switch to dark mode

        # Palette toggle for dark mode
        -   scheme: slate
            primary: deep-purple
            accent: pink
            toggle:
                icon: material/brightness-4
                name: Switch to light mode

    icon:
        admonition:
            info: material/alert-box-outline

    features:
        - navigation.instant
        - navigation.indexes
        - navigation.expand
        - navigation.footer
        - toc.follow
        - content.tabs.link
        - content.code.copy

plugins:
    - search

markdown_extensions:
    # Callouts
    - admonition
    - pymdownx.details
    - pymdownx.superfences

    # Tabs
    - pymdownx.superfences
    -   pymdownx.tabbed:
            alternate_style: true

    # Table of contents
    - toc:
        permalink: true

    # Tasklists
    - pymdownx.tasklist

    # HTML
    - md_in_html
    - attr_list

extra_css:
    - css/images.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fletcheaston

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fletcheaston/

nav:
    - Resume: index.md
    - Projects:
          - MyFreightCube: projects/my-freight-cube.md
          - Advent of Code:
                - 2023:
                    - projects/advent-of-code/2023/index.md
                    - "Day 1: Trebuchet?!": projects/advent-of-code/2023/day-1.md
                    - "Day 2: Code Conundrum": projects/advent-of-code/2023/day-2.md
          - Advent of TypeScript:
                - 2023:
                    - projects/advent-of-typescript/2023/index.md
                    - "Day 1: Christmas Cookies": projects/advent-of-typescript/2023/day-1.md
                    - "Day 2: Christmas Cookie Inventory": projects/advent-of-typescript/2023/day-2.md
