# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Fletcher Easton
site_dir: "build"

watch:
    - docs

theme:
    name: material
    logo: images/logo.png
    favicon: images/favicon.ico
    custom_dir: overrides

    palette:
        # Palette for light mode
        -   scheme: default
            primary: deep-purple
            accent: pink
            toggle:
                icon: material/brightness-7
                name: Switch to dark mode

        # Palette for dark mode
        -   scheme: slate
            primary: teal
            accent: pink
            toggle:
                icon: material/brightness-4
                name: Switch to light mode

    icon:
        admonition:
            info: material/alert-box-outline

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.indexes
        - navigation.footer
        - navigation.top
        - toc.integrate
        - toc.follow
        - content.tabs.link
        - content.code.copy

plugins:
    - search

markdown_extensions:
    # Callouts
    - admonition
    - pymdownx.details
    - pymdownx.superfences

    # Tabs
    - pymdownx.superfences
    -   pymdownx.tabbed:
            alternate_style: true

    # MathJax
    -   pymdownx.arithmatex:
            generic: true

    # Table of contents
    -   toc:
            permalink: true

    # Tasklists
    - pymdownx.tasklist

    # HTML
    - md_in_html
    - attr_list

extra_css:
    - extras/images.css
    - extras/nav.css
    - extras/blog-components.css

extra_javascript:
    - extras/mathjax.js
    - extras/blog-components.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    social:
        -   icon: fontawesome/brands/github
            link: https://github.com/fletcheaston

        -   icon: fontawesome/brands/linkedin
            link: https://www.linkedin.com/in/fletcheaston/

nav:
    -   Resume: resume.md
    -   MyFreightCube: my-freight-cube.md
    -   React in MkDocs: react-in-mkdocs.md
    -   Advent of Code - 2023:
            - advent-of-code/2023/index.md
            - advent-of-code/2023/day-1.md
            - advent-of-code/2023/day-2.md
            - advent-of-code/2023/day-3.md
            - advent-of-code/2023/day-4.md
            - advent-of-code/2023/day-5.md
            - advent-of-code/2023/day-6.md
            - advent-of-code/2023/day-7.md
            - advent-of-code/2023/day-8.md
            - advent-of-code/2023/day-9.md
            - advent-of-code/2023/day-10.md
            - advent-of-code/2023/day-11.md
            - advent-of-code/2023/day-12.md
            - advent-of-code/2023/day-13.md
    -   Advent of TypeScript - 2023:
            - advent-of-typescript/index.md
            - advent-of-typescript/2023/day-1.md
            - advent-of-typescript/2023/day-2.md
            - advent-of-typescript/2023/day-3.md
            - advent-of-typescript/2023/day-4.md
            - advent-of-typescript/2023/day-5.md
            - advent-of-typescript/2023/day-6.md
            - advent-of-typescript/2023/day-7.md
            - advent-of-typescript/2023/day-8.md
            - advent-of-typescript/2023/day-9.md
    -   Advent of Code - 2022:
            - advent-of-code/2022/index.md
            - advent-of-code/2022/day-1.md
            - advent-of-code/2022/day-2.md
            - advent-of-code/2022/day-3.md
            - advent-of-code/2022/day-4.md
            - advent-of-code/2022/day-5.md
            - advent-of-code/2022/day-6.md
            - advent-of-code/2022/day-7.md
